<?php

namespace AppBundle\Repository;

/**
 * BlogCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
