<?php

namespace AppBundle\Repository;

/**
 * compcaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class compcaseRepository extends \Doctrine\ORM\EntityRepository
{
}
