<?php

namespace AppBundle\Repository;

/**
 * coolingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coolingRepository extends \Doctrine\ORM\EntityRepository
{
}
