<?php

namespace AppBundle\Repository;

/**
 * cpuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cpuRepository extends \Doctrine\ORM\EntityRepository
{
}
