<?php

namespace AppBundle\Repository;

/**
 * gpuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gpuRepository extends \Doctrine\ORM\EntityRepository
{
}
