<?php

namespace AppBundle\Repository;

/**
 * hddRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hddRepository extends \Doctrine\ORM\EntityRepository
{
}
