<?php

namespace AppBundle\Repository;

/**
 * keyboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class keyboardRepository extends \Doctrine\ORM\EntityRepository
{
}
