<?php

namespace AppBundle\Repository;

/**
 * monitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class monitorRepository extends \Doctrine\ORM\EntityRepository
{
}
