<?php

namespace AppBundle\Repository;

/**
 * motherboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class motherboardRepository extends \Doctrine\ORM\EntityRepository
{
}
