<?php

namespace AppBundle\Repository;

/**
 * mouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mouseRepository extends \Doctrine\ORM\EntityRepository
{
}
