<?php

namespace AppBundle\Repository;

/**
 * psuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class psuRepository extends \Doctrine\ORM\EntityRepository
{
}
