<?php

namespace AppBundle\Repository;

/**
 * ramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ramRepository extends \Doctrine\ORM\EntityRepository
{
}
