<?php

namespace AppBundle\Repository;

/**
 * ssdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ssdRepository extends \Doctrine\ORM\EntityRepository
{
}
